### PR TITLE
Depends support

### PR DESCRIPTION
**Pull request by yol**
@wsnipex please quickly take a look

### CODE REVIEW

**Comment by wsnipex** [comment]
looks good to me. Only the download URLs need to be fixed once stuff was uploaded.
jenkins build this please

**Comment by yol** [comment]
Thanks! Sadly there's no jenkins here :-)

**Comment by yol** [comment]
@FernetMenta I'll merge this if you are OK with it, too

**Review by FernetMenta — APPROVED** [review]
sure

**Pull request merged**
